# Upptime config — https://upptime.js.org/docs/configuration
owner: gabek
repo: giglist-upptime

sites:
  - name: Giglist service
    url: https://gigl.ist/health

status-website:
  cname: status.gigl.ist
  name: Giglist Status
  introTitle: "**Giglist** status page"
  introMessage: Status for [gigl.ist](https://gigl.ist).
  navbar:
    - title: Status
      href: /
    - title: Giglist
      href: https://gigl.ist
